### PR TITLE
added alert stuff

### PR DESCRIPTION
**Pull request by Aelpxy**

### CODE REVIEW

**Comment by F-fengzi** [comment]
hmm

**Comment by F-fengzi** [comment]
no, if to add a warning, not there

**Comment by mobilegmYT** [comment]
get rekt fongzi

**Comment by Aelpxy** [comment]
oh wow

**Comment by F-fengzi** [comment]
~~frick~~

**Comment by F-fengzi** [comment]
have fun with the 100 user experience

**Comment by mobilegmYT** [comment]
shut

**Comment by F-fengzi** [comment]
yes owner

**Pull request merged**
