### PR TITLE
Added Particles.js to spice things up

### PR DESCRIPTION
**Pull request by Maxhu787**
## Added some particle effects

Preview the site <a href="https://maxhu787.github.io/website/">here</a>
<a href="https://vincentgarreau.com/particles.js/">Particles.js</a>

### CODE REVIEW

**Comment by NoozSBC** [comment]
why

**Comment by Maxhu787** [comment]
looks less static

**Comment by F-fengzi** [comment]
what is wrong with static >:(((

**Comment by F-fengzi** [comment]
> ## Added some particle effects
> Preview the site [here](https://maxhu787.github.io/website/) [Particles.js](https://vincentgarreau.com/particles.js/)

btw that looks wrong, sorry

**Comment by buddyjojo** [comment]
idk i kinda like it

**Comment by F-fengzi** [comment]
F

**Comment by Maxhu787** [comment]
> idk i kinda like it

nice

**Comment by IAMACAR10** [comment]
i dont like it that much

**Comment by Maxhu787** [comment]
> i dont like it that much
> 
> it doesn't fit in with the rest of the website that well. it feels like kind of a different style.

nice

**Pull request closed without merging**
