### PR TITLE
Make rickroll text comic sans

### PR DESCRIPTION
**Pull request by nobody5050**
Noon this should have been a feature all along

### CODE REVIEW

**Comment by mobilegmYT** [comment]
The rickroll text isn't displayed, I haven't been able to find why so I just edited the video itself to display the text.

**Comment by F-fengzi** [comment]
yeah nooz why that crappy text on the video it looks so bad and destroys all the humor

**Comment by F-fengzi** [comment]
> The rickroll text isn't displayed, I haven't been able to find why so I just edited the video itself to display the text.

then edit another one…?

**Comment by mobilegmYT** [comment]
> yeah nooz why that crappy text on the video it looks so bad and destroys all the humor

If you want, feel free to fix it and I can use the old video without the edited text!

**Comment by F-fengzi** [comment]
nooz why did you merge that lmao

**Pull request merged**
